[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
 miguelbalboa/MFRC522@^1.4.11
 madhephaestus/ESP32Servo@^3.0.5
 bblanchon/ArduinoJson@^7.3.0
 adafruit/Adafruit SSD1306@^2.5.13
