ServerName localhost
<Directory /var/www/html>
    Options -Indexes
    AllowOverride None
    Require all granted
    DirectoryIndex index.html
</Directory>
<Directory /opt/clack>
    Require all denied
</Directory>
