import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {DoorOpen,Layers,Users,History,Settings,Sun,Moon,LogOut,Plus,KeyRound} from 'lucide-react';
import './style.css';
let csrf='';
async function api(action,body){const r=await fetch(`../api.php?acao=${action}`,{credentials:'same-origin',method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok){const e=new Error(data.mensagem||'Falha na comunicação');e.status=r.status;throw e;}return data;}
const labels={disponivel:'Disponível',em_uso:'Em uso',manutencao:'Manutenção',erro:'Verificar',professor:'Professor',aluno:'Aluno autorizado',limpeza:'Limpeza',completo:'Acesso completo'};
function App(){
 const [op,setOp]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('salas'),[data,setData]=useState({salas:[],cartoes:[],permissoes:[],dispositivos:[],comandos:[]}),[theme,setTheme]=useState(localStorage.getItem('clack-theme')||'light'),[modal,setModal]=useState(null),[floor,setFloor]=useState(''),[history,setHistory]=useState({eventos:[],auditoria:[]}),[filter,setFilter]=useState(''),[operators,setOperators]=useState([]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('clack-theme',theme)},[theme]);
 const report=e=>{setError(e.message);if(e.status===401)setOp(null)};
 const refresh=async()=>{try{setData(await api('painel'))}catch(e){report(e)}};
 useEffect(()=>{api('sessao').then(s=>{csrf=s.csrf;setOp(s.operador)}).catch(e=>{if(e.status!==401)report(e)}).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!op)return;refresh();const t=setInterval(refresh,5000);return()=>clearInterval(t)},[op]);
 useEffect(()=>{if(op&&tab==='historico')api(`historico${filter?'&sala='+filter:''}`).then(setHistory).catch(report);if(op&&tab==='admin')api('operadores').then(d=>setOperators(d.operadores)).catch(report)},[tab,op,filter]);
 async function save(action,body){setError('');try{const r=await api(action,body);setNotice('Alteração salva. Permissões chegam às trancas na próxima sincronização.');await refresh();return r}catch(e){report(e);throw e}}
 const floors=[...new Set(data.salas.map(s=>s.andar))],currentFloor=floors.includes(floor)?floor:floors[0];
 const rooms=data.salas.filter(s=>s.andar===currentFloor);
 if(loading)return <main className="login"><p>Carregando Clack…</p></main>;
 if(!op)return <main className="login"><form className="login-card" onSubmit={async e=>{e.preventDefault();setError('');const f=new FormData(e.target);try{const s=await api('login',Object.fromEntries(f));csrf=s.csrf;setOp(s.operador)}catch(e){report(e)}}}><div className="brand"><DoorOpen/> clack<span>PORTARIA</span></div><h1>Bem-vindo à portaria.</h1><p>Entre para acompanhar os ambientes e gerenciar acessos.</p><label>Login<input name="login" autoComplete="username" required/></label><label>Senha<input name="senha" type="password" autoComplete="current-password" required/></label>{error&&<p role="alert" className="error">{error}</p>}<button>Entrar</button><small>Uso local · IFSul</small></form></main>;
 return <div className="shell"><aside><div className="brand"><DoorOpen/> clack</div><span className="eyebrow">CONTROLE DE ACESSO</span><nav>{[['salas',Layers,'Ambientes'],['cartoes',Users,'Cartões'],['historico',History,'Histórico'],...(op.papel==='admin'?[['admin',Settings,'Configurações']]:[])].map(([key,Icon,label])=><button className={tab===key?'selected':''} key={key} onClick={()=>setTab(key)}><Icon size={19}/>{label}</button>)}</nav><div className="account"><strong>{op.nome}</strong><small>{op.papel==='admin'?'Administrador':'Portaria'}</small><button className="quiet" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={17}/>:<Sun size={17}/>}Modo {theme==='light'?'escuro':'claro'}</button><button className="quiet" onClick={()=>api('logout',{}).then(()=>{csrf='';setOp(null)}).catch(report)}><LogOut size={17}/>Sair</button></div></aside><main><header><div><span className="eyebrow">CLACK / {tab==='salas'?'VISÃO GERAL':tab.toUpperCase()}</span><h1>{{salas:'Ambientes do campus',cartoes:'Cartões de acesso',historico:'Histórico de atividades',admin:'Configurações'}[tab]}</h1></div><span className="local"><i/>Servidor local</span></header>{error&&<div role="alert" className="error">{error}<button className="quiet" onClick={()=>setError('')}>Fechar</button></div>}{notice&&<div role="status" className="notice">{notice}<button className="quiet" onClick={()=>setNotice('')}>Fechar</button></div>}
 {tab==='salas'&&<><div className="stats">{['disponivel','em_uso','manutencao'].map(state=><section key={state}><span className={'dot '+state}/><span>{labels[state]}</span><strong>{data.salas.filter(s=>s.estado===state).length}</strong></section>)}<section><span>Sem conexão recente</span><strong>{data.salas.filter(s=>!Number(s.online)).length}</strong></section></div><section className="panel"><div className="toolbar"><div><h2>Mapa dos ambientes</h2><p>Mapa esquemático configurável. A planta do campus ainda precisa ser fornecida.</p></div><select aria-label="Andar" value={currentFloor||''} onChange={e=>setFloor(e.target.value)}>{floors.map(f=><option key={f}>{f}</option>)}</select></div>{rooms.length?<svg className="map" viewBox="0 0 1000 1000" aria-label={'Ambientes de '+currentFloor}>{rooms.map(s=><g key={s.id} role="button" tabIndex="0" aria-label={`${s.nome}: ${labels[s.estado]}`} onClick={()=>setModal({kind:'room',value:s})} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setModal({kind:'room',value:s})}}}><rect x={s.x} y={s.y} width="140" height="120" rx="10" className={'room '+s.estado}/><text x={Number(s.x)+12} y={Number(s.y)+35}>{s.nome.slice(0,18)}</text><text className="map-sub" x={Number(s.x)+12} y={Number(s.y)+62}>{labels[s.estado]}</text><text className="map-sub" x={Number(s.x)+12} y={Number(s.y)+91}>{Number(s.online)?'Online':'Último estado'}</text></g>)}</svg>:<div className="empty"><Layers/><h3>Nenhum ambiente cadastrado</h3><p>Cadastre salas e vincule os dispositivos em Configurações.</p></div>}</section><div className="room-grid">{data.salas.map(s=><button className="room-card" key={s.id} onClick={()=>setModal({kind:'room',value:s})}><span className={'badge '+s.estado}>{labels[s.estado]}</span><h3>{s.nome}</h3><p>{s.andar} · {s.responsavel_nome||'Sem responsável'}</p><small>{Number(s.online)?'Dispositivo conectado':'Offline / não configurado'}</small></button>)}</div><p className="muted">Estados representam a atividade registrada. O projeto ainda não possui sensor de porta ou confirmação mecânica da tranca.</p></>}
 {tab==='cartoes'&&<section className="panel"><div className="toolbar"><p>Perfis predefinidos, permissões ajustadas por ambiente.</p><button onClick={()=>setModal({kind:'card',value:null})}><Plus size={17}/>Novo cartão</button></div><div className="table-wrap"><table><thead><tr><th>Pessoa</th><th>Perfil</th><th>Cartão</th><th>Situação</th><th/></tr></thead><tbody>{data.cartoes.map(c=><tr key={c.id}><td><strong>{c.nome}</strong><small>{Number(c.externo)?'Externo · NDA':c.matricula}</small></td><td>{labels[c.perfil]}</td><td>{c.uid||'Desvinculado'}</td><td>{Number(c.ativo)?'Ativo':'Bloqueado'}</td><td><button className="quiet" onClick={()=>setModal({kind:'card',value:c})}>Editar</button></td></tr>)}</tbody></table></div>{!data.cartoes.length&&<div className="empty">Os cartões cadastrados aparecerão aqui.</div>}</section>}
 {tab==='historico'&&<><section className="panel"><div className="toolbar"><h2>Eventos dos dispositivos</h2><select aria-label="Filtrar sala" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas as salas</option>{data.salas.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select><button className="quiet" onClick={()=>api(`historico${filter?'&sala='+filter:''}`).then(setHistory).catch(report)}>Atualizar</button></div><div className="table-wrap"><table><thead><tr><th>Horário do evento</th><th>Sala</th><th>Pessoa</th><th>Resultado</th><th>Recebido</th></tr></thead><tbody>{history.eventos.map(e=><tr key={e.id}><td>{date(e.ocorrido_em)}</td><td>{e.sala}</td><td>{e.nome||'Portaria / sistema'}</td><td>{e.resultado}</td><td>{date(e.recebido_em)}</td></tr>)}</tbody></table></div>{history.eventos.length===100&&<button className="quiet" onClick={()=>api(`historico&antes=${history.eventos.at(-1).id}${filter?'&sala='+filter:''}`).then(setHistory).catch(report)}>Eventos anteriores</button>}<p className="muted">Sem relógio válido no dispositivo, o horário do evento fica desconhecido; a ordem é preservada pela sequência.</p></section><section className="panel"><h2>Ações da portaria</h2>{history.auditoria.map(a=><div className="audit" key={a.id}><strong>{a.operador}</strong><span>{a.acao.replaceAll('_',' ')}</span><small>{date(a.criado_em)}</small></div>)}</section></>}
 {tab==='admin'&&<><section className="panel"><div className="toolbar"><h2>Ambientes e dispositivos</h2><div className="actions"><button onClick={()=>setModal({kind:'environment',value:null})}>Cadastrar sala</button><button className="secondary" onClick={()=>setModal({kind:'device'})}>Cadastrar dispositivo</button></div></div>{data.salas.map(s=><div className="audit" key={s.id}><strong>{s.nome}</strong><span>{s.andar} · {s.categoria}</span><button className="quiet" onClick={()=>setModal({kind:'environment',value:s})}>Editar posição</button></div>)}{data.dispositivos.map(d=><div className="audit" key={'d'+d.id}><KeyRound size={17}/><strong>#{d.id} {d.nome}</strong><span>{d.tipo}</span><small>{date(d.ultima_conexao)}</small></div>)}</section><section className="panel"><div className="toolbar"><h2>Contas da portaria</h2><button onClick={()=>setModal({kind:'operator'})}>Nova conta</button></div>{operators.map(o=><div className="audit" key={o.id}><strong>{o.nome}</strong><span>{o.papel} · {Number(o.ativo)?'Ativo':'Bloqueado'}</span>{o.id!==op.id&&Number(o.ativo)>0&&<button className="quiet" onClick={()=>{if(confirm('Bloquear acesso de '+o.nome+'?'))save('bloquear_operador',{id:o.id}).then(()=>api('operadores')).then(d=>setOperators(d.operadores)).catch(()=>{})}}>Bloquear</button>}</div>)}</section></>}
 </main>{modal&&<div className="overlay" onClick={e=>{if(e.target===e.currentTarget)setModal(null)}}><section className="dialog" role="dialog" aria-modal="true" aria-label="Detalhes e cadastro"><button className="close quiet" aria-label="Fechar" onClick={()=>setModal(null)}>×</button>{modal.kind==='room'?<Room room={data.salas.find(s=>s.id===modal.value.id)||modal.value} commands={data.comandos} save={save}/>:modal.kind==='card'?<Card value={modal.value} data={data} save={save} report={report} close={()=>setModal(null)}/>:<Setup kind={modal.kind} value={modal.value} data={data} save={save} close={()=>{setModal(null);if(tab==='admin')api('operadores').then(d=>setOperators(d.operadores)).catch(report)}}/>}</section></div>}</div>
}
function date(s){return s?new Date(s.replace(' ','T')+'Z').toLocaleString('pt-BR'):'Desconhecido'}
function Room({room:s,commands,save}){return <><span className={'badge '+s.estado}>{labels[s.estado]}</span><h2>{s.nome}</h2><p>{s.andar} · {s.responsavel_nome||'Sem responsável'}</p><p>Última conexão: {date(s.ultima_conexao)}</p><p>Intervenções ficam registradas em seu nome. A confirmação indica execução do comando pelo dispositivo, sem sensor mecânico.</p><div className="actions">{[['abrir','Destrancar'],['fechar','Encerrar e trancar'],['manutencao','Trancar para manutenção'],['liberar','Encerrar manutenção']].map(([cmd,label])=><button key={cmd} disabled={!Number(s.online)} onClick={()=>{if(confirm(label+' '+s.nome+'?'))save('comando',{sala:s.id,comando:cmd}).catch(()=>{})}}>{label}</button>)}</div><h3>Comandos recentes</h3>{commands.filter(c=>c.dispositivo_id===s.dispositivo_id).slice(0,5).map(c=><p key={c.id}>{c.acao} · {c.confirmado_em?'Confirmado pelo dispositivo':new Date(c.expira_em.replace(' ','T')+'Z')<new Date()?'Expirado':'Aguardando confirmação'}</p>)}</>}
function Card({value,data,save,report,close}){const [form,setForm]=useState(value?{...value,externo:!!Number(value.externo),ativo:!!Number(value.ativo),salas:data.permissoes.filter(p=>p.cartao_id===value.id).map(p=>p.ambiente_id)}:{nome:'',matricula:'',externo:false,perfil:'professor',ativo:true,salas:data.salas.filter(s=>s.categoria==='aula').map(s=>s.id)}),[reader,setReader]=useState(data.dispositivos.find(d=>d.tipo==='cadastrador')?.id||''),[capture,setCapture]=useState(''),[uid,setUid]=useState('');
 useEffect(()=>{if(!capture)return;const t=setInterval(()=>api('ler_captura',{captura:capture}).then(d=>setUid(d.uid||'')).catch(e=>{report(e);setCapture('')}),1000);return()=>clearInterval(t)},[capture]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 return <form onSubmit={e=>{e.preventDefault();save('cartao',{...form,...(capture?{captura:capture}:{})}).then(close).catch(()=>{})}}><h2>{value?'Editar cartão':'Cadastrar cartão'}</h2><label>Nome<input required maxLength="100" value={form.nome} onChange={e=>set('nome',e.target.value)}/></label><label className="check"><input type="checkbox" checked={form.externo} onChange={e=>set('externo',e.target.checked)}/>Pessoa externa (NDA)</label>{!form.externo&&<label>Matrícula<input required maxLength="50" value={form.matricula||''} onChange={e=>set('matricula',e.target.value)}/></label>}<label>Perfil<select value={form.perfil} onChange={e=>set('perfil',e.target.value)}>{['professor','aluno','limpeza','completo'].map(p=><option key={p} value={p}>{labels[p]}</option>)}</select></label><h3>Salas permitidas</h3><div className="actions"><button type="button" className="quiet" onClick={()=>set('salas',data.salas.filter(s=>s.categoria==='aula').map(s=>s.id))}>Salas de aula</button><button type="button" className="quiet" onClick={()=>set('salas',data.salas.map(s=>s.id))}>Todas</button><button type="button" className="quiet" onClick={()=>set('salas',[])}>Limpar</button></div><div className="room-options">{data.salas.map(s=><label className="check" key={s.id}><input type="checkbox" checked={form.salas.includes(s.id)} onChange={e=>set('salas',e.target.checked?[...form.salas,s.id]:form.salas.filter(id=>id!==s.id))}/>{s.nome} · {s.andar}</label>)}</div><small>O perfil não concede salas automaticamente. Confira a seleção acima.</small><label className="check"><input type="checkbox" checked={form.ativo} onChange={e=>set('ativo',e.target.checked)}/>Cartão ativo</label><fieldset><legend>Leitura na portaria</legend><select aria-label="Cadastrador" value={reader} onChange={e=>setReader(Number(e.target.value))}><option value="">Selecione um cadastrador</option>{data.dispositivos.filter(d=>d.tipo==='cadastrador').map(d=><option key={d.id} value={d.id}>{d.nome}</option>)}</select><button type="button" className="secondary" disabled={!reader||!!capture} onClick={()=>api('capturar',{dispositivo:reader}).then(d=>setCapture(d.captura)).catch(report)}>Iniciar leitura</button><p>{uid?'Cartão lido: '+uid:capture?'Aproxime o cartão (até 2 minutos).':value?.uid||'Nenhum cartão lido'}</p></fieldset><div className="actions"><button disabled={!!capture&&!uid}>Salvar cadastro</button>{value&&<button type="button" className="danger" onClick={()=>{if(confirm('Desvincular este cartão? O histórico será preservado.'))save('resetar_cartao',{id:value.id}).then(close).catch(()=>{})}}>Desvincular cartão</button>}</div></form>
}
function Setup({kind,value,data,save,close}){const [result,setResult]=useState(null);return <form onSubmit={e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));if(value)b.id=value.id;if(kind==='environment'){b.x=Number(b.x);b.y=Number(b.y)}if(kind==='device'&&b.sala)b.sala=Number(b.sala);save({environment:'sala',operator:'operador',device:'dispositivo'}[kind],b).then(r=>kind==='device'?setResult(r):close()).catch(()=>{})}}><h2>{{environment:'Configurar ambiente',operator:'Conta da portaria',device:'Novo dispositivo'}[kind]}</h2>{result?<><p>Guarde esta credencial no arquivo local do dispositivo. Ela só aparece nesta resposta.</p><label>ID<input readOnly value={result.id}/></label><label>Token<textarea readOnly value={result.token}/></label><button type="button" onClick={close}>Concluir</button></>:<><label>Nome<input name="nome" required maxLength={kind==='environment'?50:100} defaultValue={value?.nome}/></label>{kind==='environment'&&<><label>Andar<input name="andar" required defaultValue={value?.andar||'Térreo'} maxLength="50"/></label><label>Categoria<select name="categoria" defaultValue={value?.categoria||'aula'}><option value="aula">Sala de aula</option><option value="administrativa">Administrativa</option><option value="outra">Outra</option></select></label><p>Posição no mapa esquemático (0–850). Cada sala ocupa 140 × 120 unidades.</p><div className="actions"><label>X<input name="x" type="number" min="0" max="850" defaultValue={value?.x??(data.salas.length%5)*180}/></label><label>Y<input name="y" type="number" min="0" max="850" defaultValue={value?.y??Math.min(850,Math.floor(data.salas.length/5)*160)}/></label></div></>}{kind==='operator'&&<><label>Login<input name="login" required autoComplete="off"/></label><label>Senha inicial<input name="senha" type="password" minLength="12" maxLength="72" required autoComplete="new-password"/></label><label>Papel<select name="papel"><option value="portaria">Portaria</option><option value="admin">Administrador</option></select></label></>}{kind==='device'&&<><label>Tipo<select name="tipo"><option value="tranca">Tranca</option><option value="cadastrador">Cadastrador</option></select></label><label>Sala (apenas tranca)<select name="sala"><option value="">Selecione</option>{data.salas.filter(s=>!s.dispositivo_id).map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></label></>}<button>Salvar</button></>}</form>}
createRoot(document.getElementById('root')).render(<App/>);
